/*定義action類型*/
const ADD_TODO = 'ADD_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'


export { ADD_TODO,REMOVE_TODO,TOGGLE_TODO,SET_VISIBILITY_FILTER }